export const MOVIES_FETCH_REQUEST = 'MOVIES_FETCH_REQUEST';
export const MOVIES_FETCH_SUCCESS = 'MOVIES_FETCH_SUCCESS';
export const MOVIES_FETCH_ERROR = 'MOVIES_FETCH_ERROR';
export const MOVIES_FILTER = 'MOVIES_FILTER';
export const MOVIES_SEARCH = 'MOVIES_SEARCH';
